data:
  data_root: /kaggle/input/datasets/xingyushen666/abide-fc-three-atlas
  atlases:
    aal:
      num_nodes: 116
      fc_file: X_aal.npy
    cc200:
      num_nodes: 200
      fc_file: X_cc200.npy
    ho:
      num_nodes: 111
      fc_file: X_ho.npy

train:
  seeds: [0, 1, 2, 3, 4]
  n_splits: 5
  epochs: 80
  batch_size: 32
  lr: 1.0e-3
  weight_decay: 1.0e-4
  use_best_val: false

model:
  hidden_dim: 128
  embedding_dim: 128
  num_signed_layers: 2
  dropout: 0.5
  temperature: 1.0
  add_negative_self_loops: true

loss:
  lambda_branch: 0.2
  lambda_reg: 0.1
  margin: 0.1
  regularization_mode: fusion_better
